pure JDBC and Hibernate(Spring JPA)
inventorsoft-academy/db-access pull request #31
Opened 2021-11-08 12:26 UTC by tsiupa-coder

2021-11-16 07:07 UTC, vova-pereb requested changes

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/pom.xml
> +                    <source>16</source>
There is difference in Java version in properties and source/target.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/Main.java
> +@SpringBootApplication
_org.springframework.boot.autoconfigure.SpringBootApplication#proxyBeanMethods_
Always good to set false if possible.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +import org.springframework.web.bind.annotation.*;
Avoid import everyhing from the package.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +@RequiredArgsConstructor
Unused.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +        Team team1 = teamService.createTestTeam();
Controller should not be responsible for data initialization.
Create your own _org.springframework.stereotype.Component_

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    public ResponseEntity<Game> games(@PathVariable Integer id) {
Use meaningfull name for the controller method.
In this case it would be better to call it: `getGameById`.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    @GetMapping(value = "/teams")
It would be better to use multiple controllers: `GameController`, `TeamController`, etc...

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    @PostMapping(value = "/admin/new/tournament/{name}")
You do not need to use `new` or `create` in endpoint name.
REST API allows you to use HTTP method.
Example: `POST /tournaments` it will be always treated by everyone as create new resource in _tournaments_ collection.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    public ResponseEntity<Tournament> createTournament(@PathVariable String name, @RequestBody ArrayList<Team> teams){
Prefer interface prior to concrete implementation.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    public ResponseEntity<Tournament> createTournament(@PathVariable String name, @RequestBody ArrayList<Team> teams){
Format code properly.
Rules are here: https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +
Remove empty space.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/configuration/PersistenceConfig.java
> +@Configuration()
Remove brackets.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +    @ManyToOne(fetch = FetchType.EAGER, optional = false)
Avoid _EAGER_ fetch strategy.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +    @ManyToOne()
Remove brackets.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +        return round + " " + teamFirst.getName() +
It would be better to use _java.lang.String#format(java.lang.String, java.lang.Object...)_
This way you can predict the output.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +    public Team Winner() {
Method name should be starting with lowercase letter.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +        for (int i = 0; i < str.length; i++)
Java code conventions...
1) This method is not that simple and you explicitly made it even more complex to understand (no formatting).
2) Prefer to have single exit point from the method.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Game.java
> +    public boolean equals(Object o) {
It will be better if you use Lombok / org.apache.commons.lang3.builder.EqualsBuilder
Usually these solutions handle it the best.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Team.java
> +import javax.persistence.*;
Remove.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Team.java
> +    @Column(nullable = false)
It is always nice to have some constraints.
I do not think that team name of 255 symbols is something close to reality.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/model/Tournament.java
> +@Table(name = "TOURNAMENT")
Redundant

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/GameService.java
> +    GameRepository gameRepository;
Field incapsulation maybe?

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/GameService.java
> +    public GameService( GameRepository gameRepository) {
Code formatiing.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/GameService.java
> +        for (String s : listOfGames.keySet())
Code conventions.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TeamService.java
> +    TeamRepository teamRepository;
The same here.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TeamService.java
> +        register(teams);
Code formatting.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TournamentService.java
> +import java.util.List;
Between imports and class declaration there should be single empty line.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TournamentService.java
> +    TournamentRepository tournamentRepository;
Same here.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TournamentService.java
> +    @Transactional
Empty line after end of the method.

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/TournamentService.java
> +    public Tournament createTestTournament() {
Why not to reuse your own method with name as argument?

2021-11-16 07:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/domain/service/base/GeneralService.java
> +
Empty line here is no necessary.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/pom.xml
> +		<java.version>11</java.version>
Please use latest Java.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/pom.xml
> +		<dependency>
Duplicate.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +import java.util.*;
Same here.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    Controller(DataStore dataStore){
This can be replaced with lombok.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +
What is the purpose of empty line here?

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    public ResponseEntity<List<Team>> team(@PathVariable(value = "id") Integer id) {
_org.springframework.web.bind.annotation.PathVariable#value_ redundant

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +
Same here.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    public List<Object> tournament(@PathVariable Integer id) {
Object means anything.
This is bad style of writing controller endpoint.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +    @Autowired
Annotation is redundant.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +        String initSql = getSqlCode("init.sql");
https://stackoverflow.com/a/41644743

org.springframework.jdbc.datasource.init.DatabasePopulatorUtils

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +    Statement statement;
Unused.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +        PreparedStatement preparedStatement = connection.prepareStatement(PREPARED_SQL_ALL);
Connection should be closed after each usage.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +        preparedStatement.close();
Use try with resources.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +        String query = "SELECT " +
Since Java 15 you can use Text blocks.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +                        "INSERT INTO TEAMS (NAME, CAPTAIN, COACH) VALUES(?, ?, ?)",
To improve readability you should create atomic operations: `createTeam`, `createGame`, and so on...

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DBDataStore.java
> +        String name = "", captain = "", coach = "";
Avoid single line definition.
If you need to modify something it is harder to find what you need.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/repository/DataStore.java
> +public interface DataStore {
This interface is missing in Hibernate task.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/service/TournamentService.java
> +@Component
There is _org.springframework.stereotype.Service_.
Why component?

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/service/TournamentService.java
> +    HashMap<String, List<Game>> listOfGames = new HashMap<>();
map != list : )

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/resources/init.sql
> +    ID smallint PRIMARY KEY NOT NULL IDENTITY,
Not a good type for the id.

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/resources/insert.sql
> +INSERT INTO TOURNAMENT (ID, NAME) VALUES (0, 'UEFA Champions League');
First id should start from `1`

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/main/resources/script.sql
> +CREATE TABLE IF NOT EXISTS NATIONALITY
What this file is doing here?

2021-11-16 07:07 UTC, vova-pereb commented on spring-boot-task/src/test/java/com/example/task5/Task5ApplicationTests.java
> +class Task5ApplicationTests {
What is the purpose of this "test"?

2021-11-18 18:59 UTC, tsiupa-coder commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    public ResponseEntity<Tournament> createTournament(@PathVariable String name, @RequestBody ArrayList<Team> teams){
if it about ArrayList, i tried to use List but get exeption, something like can't find constructor for List

2021-11-18 21:43 UTC, tsiupa-coder commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    public List<Object> tournament(@PathVariable Integer id) {
I use Object because this endpoint returns List which contains Tournament and List of Games.

2021-11-18 21:44 UTC, tsiupa-coder commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    public List<Object> tournament(@PathVariable Integer id) {
what is the best way in this situation?

2021-11-19 06:07 UTC, vova-pereb commented on hibernate/src/main/java/com/inventorsoft/author/Controller.java
> +    public ResponseEntity<Tournament> createTournament(@PathVariable String name, @RequestBody ArrayList<Team> teams){
Try once more, probably there were issues with `Team`.
Spring knows how to instantiate `ArrayList`.

2021-11-19 06:10 UTC, vova-pereb commented on spring-boot-task/src/main/java/com/example/task5/controllers/Controller.java
> +    public List<Object> tournament(@PathVariable Integer id) {
You have endpoint called: `tournament/id`.
It means that people would expect that `Tournament` entity will be returned.
So it should be `List<Tournament>`.

If you need to have response combined with multiple entities - use wrapper.

```
class MyDto {
    private Class1 class1;
    private Class2 class2;
}
```

2022-01-24 13:09 UTC, closed without merging