Hibernate
inventorsoft-academy/db-access pull request #35
Opened 2021-11-29 23:57 UTC by Panic7

2021-11-30 09:05 UTC, vova-pereb requested changes

2021-11-30 09:05 UTC, vova-pereb commented on src/main/java/com/example/demo/DemoApplication.java
> +        console.getTournament().getTeamService().saveAll(List.of(
This breaks DI.
Beans should never be accessed by getters.

2021-11-30 09:05 UTC, vova-pereb commented on src/main/java/com/example/demo/model/Match.java
> +    @ManyToOne(fetch = FetchType.EAGER, optional = false)
Eager fetch type is forbidden.

2021-11-30 09:05 UTC, vova-pereb commented on src/main/java/com/example/demo/service/base/GeneralService.java
> +    public ENTITY getById(ID id) {
`org.springframework.transaction.annotation.Transactional`
Should be used if you access DB.

2021-11-30 09:05 UTC, vova-pereb commented on src/test/java/com/example/demo/DemoApplicationTests.java
> +class DemoApplicationTests {
Redundant

2021-12-01 16:26 UTC, Panic7 commented
@vova-pereb

2022-01-24 13:10 UTC, closed without merging