HomeTask8 done
inventorsoft-academy/db-access pull request #39
Opened 2022-04-07 15:19 UTC by Rllst

2022-04-07 22:24 UTC, Rllst commented
Done hw8

2022-04-14 11:40 UTC, vova-pereb requested changes

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/Main.java
> +        JdbcUtils jdbcUtils=new JdbcUtils();
Format code properly.

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/dao/impl/MatchDaoImpl.java
> +        final String SQL_FIND_MATCH="SELECT * FROM MATCHES WHERE ID=?";
Avoid `select *`

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/dao/impl/MatchDaoImpl.java
> +            statement.close();
Use try with resources.

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/dao/impl/MatchDaoImpl.java
> +        final String SQL_UPDATE_MATCH="UPDATE MATCHES SET TOURNAMENTID=?, FIRSTTEAMID=?, SECONDTEAMID=?," +
Multiline string will be better here.

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/entity/Match.java
> +        return "id:" + id + " tourID:" + tournamentId + " firstTeam:" + firstTeamId +
In case of complex patterns I prefer to use `java.lang.String#format(java.lang.String, java.lang.Object...)`

2022-04-14 11:40 UTC, vova-pereb commented on src/main/java/jdbc/JdbcUtils.java
> +            Statement statement = getConnection().createStatement();
`java.sql.Statement#close`
Do not forget about it.

2022-09-22 06:46 UTC, closed without merging